changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - imgbot
  categories:
    - title: New Pages
      labels:
        - new
    - title: Updated Pages
      labels:
        - update
    - title: Infrastructure Updates
      labels:
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
