# Project information
site_name: Patrick's Notes
site_author: Patrick Creighton

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    # - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

# Customization
extra:
  social:
    - icon: material/github
      link: https://github.com/patrick-5546
    - icon: material/linkedin
      link: https://www.linkedin.com/in/patrick-5546/
    - icon: material/email
      link: mailto:pcreighton429@gmail.com

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Setup:
    - setup/index.md
    - Terminal:
      - setup/terminal/index.md
      - PowerShell: setup/terminal/powershell.md
      - Zsh: setup/terminal/zsh.md
    - IDE: setup/ide.md
    - Other Software: setup/software.md
  - About Me: https://www.linkedin.com/in/patrick-5546/
