# Project information
site_name: Patrick's Notes
site_url: https://patrick-5546.github.io/notes/
site_author: Patrick Creighton

# Repository
repo_name: patrick-5546/notes
repo_url: https://github.com/patrick-5546/notes
edit_uri: ""

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      timezone: America/Vancouver

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: material/github
      link: https://github.com/patrick-5546
    - icon: material/linkedin
      link: https://www.linkedin.com/in/patrick-5546/
    - icon: material/email
      link: mailto:pcreighton429@gmail.com

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Setup:
    - setup/index.md
    - Terminal:
      - setup/terminal/index.md
      - PowerShell: setup/terminal/powershell.md
      - Zsh: setup/terminal/zsh.md
    - IDE: setup/ide.md
    - Other Software: setup/software.md
  - Internship Preparation:
    - internship_prep/index.md  # disclaimer: not a learning resource, but for brush up / review / knowledge check
    - Applications: internship_prep/applications.md
    - Interview Preparation: internship_prep/interview_prep.md
    - Hardware Interviews:
      - Reference: internship_prep/hardware/hw_reference.md  # definitions list for each topic, use abbreviations
      - Questions: internship_prep/hardware/hw_questions.md
    - Software Interviews:
      - Reference: internship_prep/software/sw_reference.md
      - Questions: internship_prep/software/sw_questions.md
  - Reference:
    - Bookmarks: reference/bookmarks.md
    - Git:
      - Git Contribution Process: reference/git/git_contributing.md
      - Git Commands: reference/git/git_commands.md
    - Linux Commands: reference/linux.md
    - Material for MkDocs: reference/mkdocs.md
    - Python: reference/python.md
    - SSH: reference/ssh.md
    - Windows Shortcuts: reference/shortcuts.md
    - WSL: reference/wsl.md
  - About Me: profile.md
