# Project information
site_name: Patrick's Notes
site_url: https://patrick-5546.github.io/notes/
site_author: Patrick Creighton

# Repository
repo_name: patrick-5546/notes
repo_url: https://github.com/patrick-5546/notes
edit_uri: ""

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:

# Customization
extra:
  social:
    - icon: material/github
      link: https://github.com/patrick-5546
    - icon: material/linkedin
      link: https://www.linkedin.com/in/patrick-5546/
    - icon: material/email
      link: mailto:pcreighton429@gmail.com

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Setup:
    - setup/index.md
    - Terminal:
      - setup/terminal/index.md
      - PowerShell: setup/terminal/powershell.md
      - Zsh: setup/terminal/zsh.md
    - IDE: setup/ide.md
    - Other Software: setup/software.md
  - Reference:
    - Docker: reference/docker.md
    - Git:
      - Contributing: reference/git/contributing.md
      - Features: reference/git/git_features.md
    - Windows Keyboard Shortcuts: reference/shortcuts.md
    - Linux Commands: reference/linux.md # pipe, chmod, du, export, ls, less (reference aliases)
    - Mkdocs: reference/mkdocs.md  # why use mkdocs (can focus on writing, but not as customizable)
    - Python: reference/python.md
    - SSH: reference/ssh.md
    - WSL: reference/wsl.md
  - About Me: https://www.linkedin.com/in/patrick-5546/
