name: Deploy Docs

on:
  push:
    branches: 
      - main

jobs:
  # https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'  # checkout all commits to get the actual page revision time

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache social plugin files
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install OS dependencies
        run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev

      - name: Install Python dependencies
        run: pip install -r docs/requirements.txt

      - name: Deploy MkDocs application with mike
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          git config user.name ci-bot
          git config user.email pcreighton429@gmail.com
          mike deploy --push devel
