name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # https://github.com/avto-dev/markdown-lint
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint website markdown pages
      uses: avto-dev/markdown-lint@v1.5.0
      with:
        config: '.markdownlint.json'
        args: 'docs/* includes/*'
