name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # https://github.com/nosborn/github-action-markdown-cli
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint markdown pages
      uses: nosborn/github-action-markdown-cli@v3.0.1
      with:
        files: 'docs/* includes/*'
        config_file: '.markdownlint.json'
